import type { NextPage } from 'next';
import Head from 'next/head';
import Script from 'next/script';
import styles from 'styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Uptime Checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-6xl font-bold">Welcome to Uptime Checker!</h1>
        <p className={styles.description}>Launching Soon....</p>
      </main>
    </div>
  );
};

export default Home;
