import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="py-0 px-10">
      <Head>
        <title>Uptime Checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col justify-center py-10 px-0 text-center">
        <h1 className="text-6xl font-bold">Welcome to Uptime Checker!</h1>
        <p className="my-10 mx-0 text-center text-2xl">Launching Soon....</p>
      </main>
    </div>
  );
};

export default Home;
